# Generated by Django 4.2 on 2023-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_alter_menu_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="URL"),
        ),
    ]
